package com.solvind.skycams.app.core

/**
 * Service
 * */
const val SERVICE_CANCEL_ALL_ALARM_INTENT_ACTION = "clear_all_alarms"

const val SERVICE_SELECT_NEXT_ALARM_REQUEST_CODE = 200
const val SERVICE_SELECT_PREVIOUS_ALARM_REQUEST_CODE = 201
const val SERVICE_CANCEL_ALL_ALARMS_REQUEST_CODE = 203

const val SERVICE_CANCEL_SINGLE_ALARM_REQUEST_CODE = 204
const val SERVICE_TOGGLE_LIVE_VIEW_REQUEST_CODE = 205

const val SERVICE_SELECT_NEXT_ALARM_ACTION = "SERVICE_SELECT_NEXT_ALARM_ACTION"
const val SERVICE_SELECT_PREVIOUS_ALARM_ACTION = "SERVICE_SELECT_PREVIOUS_ALARM_ACTION"
const val SERVICE_CANCEL_SINGLE_ALARM_ACTION = "SERVICE_CANCEL_SINGLE_ALARM_ACTION"
const val SERVICE_TOGGLE_LIVE_VIEW_ACTION = "SERVICE_TOGGLE_LIVE_VIEW_ACTION"

const val SERVICE_FOREGROUND_NOTIFICATIONS_CHANNEl_ID = "SERVICE_FOREGROUND_NOTIFICATIONS_CHANNEl_ID"
const val SERVICE_ALARM_NOTIFICATIONS_CHANNEL_ID = "SERVICE_ALARM_NOTIFICATIONS_CHANNEL_ID"
const val SERVICE_ALARM_TIMEOUT_NOTIFICATION_CHANNEL_ID = "SERVICE_ALARM_TIMEOUT_NOTIFICATION_CHANNEL_ID"
const val SERVICE_FOREGROUND_NOTIFICATION_ID = 900

/**
 * Activity
 * */
const val ACTIVITY_OPEN_SINGLE_SKYCAM_REQUEST_CODE = 100
const val ACTIVITY_WATCH_AD_REQUEST_CODE = 101
const val ACTIVITY_OPEN_SINGLE_SKYCAM_ACTION ="ACTIVITY_OPEN_SINGLE_SKYCAM"
const val ACTIVITY_WATCH_AD_INTENT_ACTION = "ACTIVITY_WATCH_AD_INTENT_ACTION"

/**
 * ALL
 * */
const val INTENT_EXTRA_SKYCAMKEY = "skycamKey"
const val INTENT_EXTRA_SKYCAM_NAME = "skycamName"
const val INTENT_EXTRA_SKYCAM_MAIN_IMAGE = "skycamMainImage"